version: "3"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cartola
    ports:
      - "3306:3306"

  goapp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/app
    platform: linux/amd64
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
